<a href="https://colab.research.google.com/github/Sasaki0Kojiro/hello-world/blob/main/putorch5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
%matplotlib inline

In [3]:
import torch

x = torch.ones(5)
y = torch.zeros(3)
w = torch.randn(5,3,requires_grad = True)
b = torch.randn(3,requires_grad = True)
z = torch.matmul(x,w) + b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z,y)

In [4]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.3301, 0.0193, 0.0177],
        [0.3301, 0.0193, 0.0177],
        [0.3301, 0.0193, 0.0177],
        [0.3301, 0.0193, 0.0177],
        [0.3301, 0.0193, 0.0177]])
tensor([0.3301, 0.0193, 0.0177])


In [5]:
z = torch.matmul(x,w)+b
print(z.requires_grad)
with torch.no_grad():
  z = torch.matmul(x,w)+b
print(z.requires_grad)

True
False


In [6]:
z = torch.matmul(x,w) + b
z_det = z.detach()
print(z_det.requires_grad)

False


In [9]:
inp = torch.eye(5,requires_grad=True)
out = (inp + 1).pow(2)
out.backward(torch.ones_like(inp),retain_graph=True)
print("First call\n",inp.grad)
out.backward(torch.ones_like(inp),retain_graph=True)
print("Second call\n", inp.grad)
inp.grad.zero_()
out.backward(torch.ones_like(inp),retain_graph=True)
print("Last call\n",inp.grad)

First call
 tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.],
        [2., 2., 2., 2., 4.]])
Second call
 tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.],
        [4., 4., 4., 4., 8.]])
Last call
 tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.],
        [2., 2., 2., 2., 4.]])
