<a href="https://colab.research.google.com/github/Sasaki0Kojiro/hello-world/blob/main/pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%matplotlib inline

In [ ]:
import torch
import numpy as np

In [ ]:
data = [[1,2],[3,4]]

In [18]:
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [ ]:
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [ ]:
x_rand = torch.rand_like(x_data,dtype=torch.float)
x_rand

tensor([[0.6263, 0.3711],
        [0.5068, 0.2387]])

In [ ]:
shape = (2,3)
rand_tensor = torch.rand(shape)
rand_tensor

tensor([[0.8649, 0.0487, 0.8848],
        [0.7275, 0.7382, 0.9407]])

In [19]:
tensor = torch.rand(3,4)
tensor.shape
tensor.dtype
tensor.device

device(type='cpu')

In [21]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

In [23]:
tensor = torch.ones(4,4)
print(tensor[0])
print(tensor[:,0])
print(tensor[...,-1])

tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])


In [27]:
tensor[3] = 0
print(tensor)
print(tensor[3])

tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [0., 0., 0., 0.]])
tensor([0., 0., 0., 0.])


In [29]:
agg = tensor.sum()
print(agg,type(agg))
agg_item = agg.item()
print(agg_item)

tensor(9.) <class 'torch.Tensor'>
9.0


In [30]:
tensor.add_(5)
print(tensor)

tensor([[6., 6., 6., 5.],
        [6., 6., 6., 5.],
        [6., 6., 6., 5.],
        [5., 5., 5., 5.]])


In [31]:
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [32]:
t.add_(1)
print(t)
print(n)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
